### ISSUE TITLE
Ошибка при поптыки соединения с ТК

### ISSUE THREAD

**Issue by kunashir** [pomozoff/testing1c#1]
День добрый.
Получаю такую ошибку:
{Обработка.Тестирование.Форма.ФормаАвторизации(10)}: Поле объекта не обнаружено (СменитьПароль)
    НадоСменитьПароль = Соединение.ПараметрыСеанса.ТекущийПользователь.СменитьПароль;

**Comment by kunashir** [comment]
Не от туда запустил обработку!

**Comment by pomozoff** [comment]
Закрывать?
УПД: а, вижу )
