### ISSUE TITLE
Переопределить успешность теста

### ISSUE THREAD

**Issue by kunashir** [pomozoff/testing1c#2]
Добрый день!
Есть ли возможность написать свой критерий определения успешности?
Т.е. если я хочу протестировать не функцию, а процедуру, которая, скажем, что-то меняет в документе: я вызываю процедуру и проверяю некий  атрибут документа.

**Comment by pomozoff** [comment]
Да, можно.
Добавляйте кастомные результаты и напишите скрипт в поле "После выполнения", который заполнит определённые ранее кастомные результаты нужными данными из реквизитов полученного документа в процессе выполнения теста.

**Comment by kunashir** [comment]
Т.е. в таблице результатов я добавляю свой результат руками, указываю ему ожидаемое значение и в обработчике "После выполнения" уже присваиваю результаты выполнения теста?

**Comment by pomozoff** [comment]
Если я всё правильно понял, то ответ - да.

Ещё раз на всякий случай опишу методику.
Как я понимаю задача у вас такая: вызывается метод, который меняет что-то в каком-то документе, а вы хотите убедится, что состояние документа после выполнения метода соответствует каким-либо критериям.
Для решения задачи, когда тестируемый метод явно не возвращает интересуемого результата после выполнения, необходимо создать свой кастомный результат и заполнить его нужным значением, взятым в вашем случае из изменённого документа, в обработчике "После выполнения". Данный результат будет участвовать в проверке результатов теста на совпадение с эталонными значениями, если, конечно, не отключен флажок результата "Включён".

UPD. Так же можно добавлять кастомные входящие данные, в частности можно в качестве значения кастомного параметра выбрать ссылку на конкретный документ и использовать её в обрабтчике "После выполнения" чтобы избежать написания кода поиска нужного документа в базе.
